# Generated by Django 3.0 on 2020-03-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billionaire_name', models.CharField(max_length=300)),
                ('net_worth', models.DecimalField(decimal_places=2, help_text='Number in billions up to two decimal points.', max_digits=6)),
                ('net_worth_source', models.CharField(blank=True, help_text="Short name of source of net worth, e.g. 'Forbes'.", max_length=50, null=True)),
                ('net_worth_source_date', models.CharField(blank=True, help_text="Year or month and year net worth was reported, e.g. '2020' or 'March 2020'.", max_length=50, null=True)),
                ('net_worth_source_link', models.URLField(blank=True, help_text="URL of net worth source, e.g. 'https://www.forbes.com/profile/jeff-bezos/'", null=True)),
                ('billionaire_bio', models.TextField(help_text='Do not include citations here. Add those after the page is created.HTML is available, but please only use for links and basic styling.')),
                ('billionaire_pic_filename', models.CharField(default='grubman.png', help_text="Filename of image uploaded to AWS billionaires folder, e.g. 'epstein.png'.", max_length=200)),
                ('billionaire_pic_caption', models.CharField(blank=True, help_text='Image attribution and/or caption.', max_length=500, null=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['-net_worth'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(default=0)),
                ('episode_title', models.CharField(help_text='Leave out the episode number.', max_length=300)),
                ('embed', models.CharField(blank=True, help_text="On Soundcloud, click on Share, then Embed, then select the rightmost option from the three squares on the top, then copy the contents of the box labeled 'Code' and paste here.", max_length=300, null=True)),
                ('patreon_episode', models.BooleanField(default=False, help_text='Select if this is a patreon episode')),
                ('patreon_link', models.URLField(blank=True, help_text="If this is a Patreon episode, use the location of the specific episode page. e.g. 'https://www.patreon.com/posts/episode-146-eric-34650521'.", max_length=300, null=True)),
                ('episode_description', models.TextField(help_text="Do not include citations from the episode desctiption. Use the 'add citation' functionality for that. HTML is available, but please only use for links and basic styling.")),
                ('show_billionaires', models.BooleanField(default=False, help_text='Select this to display billionaires linked to this episode.')),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'ordering': ['-episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_title', models.CharField(help_text='e.g.: Jeffrey Epstein Gave Millions to Charity, Study Finds', max_length=500)),
                ('citation_publication', models.CharField(help_text="Source, e.g. 'New York Times'.", max_length=100)),
                ('citation_link', models.URLField(max_length=500)),
                ('archive_link_available', models.BooleanField(default=False, help_text='Select to display a backup link from the internet archive.')),
                ('archive_link', models.URLField(blank=True, help_text='A link from the web archive to supplement original.', max_length=500, null=True)),
                ('citation_description', models.TextField(help_text='One to two sentence overview of citation contents.')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='content.Episode')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeBillionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billionaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.Billionaire')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='BillionaireCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_title', models.CharField(help_text='e.g.: Jeffrey Epstein Gave Millions to Charity, Study Finds', max_length=500)),
                ('citation_publication', models.CharField(help_text="Source, e.g. 'New York Times'.", max_length=100)),
                ('citation_link', models.URLField(help_text='Article link.', max_length=500)),
                ('archive_link_available', models.BooleanField(default=False, help_text='Select to display a backup link from the internet archive.')),
                ('archive_link', models.URLField(blank=True, help_text='A link from the web archive to supplement original.', max_length=500, null=True)),
                ('citation_description', models.TextField(help_text='One to two sentence overview of citation contents.')),
                ('billionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='content.Billionaire')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='billionaire',
            name='episode',
            field=models.ManyToManyField(blank=True, related_name='billionaires', through='content.EpisodeBillionaire', to='content.Episode'),
        ),
    ]
